### ISSUE TITLE
iOS不能正常显示

### ISSUE THREAD

**Issue by fengshanjian** [dodola/WeexOne#10]
跑在iOS设备上，阅读与电影标签页刷不出内容，只有一个title

**Comment by dodola** [comment]
@fengshanjian 这个之前没做ios的适配，因为我写这个项目的时候还没ios版的weex发布

**Comment by fengshanjian** [comment]
阿里给出的解决办法是在list后面添加style，可以完成适配，movie.we里面修改如下
<nav-bar-normal title="电影"></nav-bar-normal>
        <list style="flex:1">

**Comment by dodola** [comment]
@fengshanjian 应该已经修复，谢谢某同学pr
