### ISSUE TITLE
建议：修改 README中 {name: ‘WeexOne/index.js’, title: ‘WeexOne’}

### ISSUE THREAD

**Issue by zeuscoder** [dodola/WeexOne#11]
README.md
Build & Run步骤中Add WeexOne to index.we
{name: ‘WeexOne/index.js’, title: ‘WeexOne’}语句语法不正确且包含中文符号，直接复制容易出错。
建议改为：{name: 'WeexOne/index', title: 'WeexOne'}

**Comment by dodola** [comment]
@zeuscoder 已经修复
