### ISSUE TITLE
最新版的weex无法require api.js

### ISSUE THREAD

**Issue by louisbao** [dodola/WeexOne#15]
代码里require到一个工具api.js，测试的时候报错如下：
[Error] TypeError: apis.getHome is not a function. (In 'apis.getHome', 'apis.getHome' is undefined)

**Comment by louisbao** [comment]
@dodola 大神，有空看一下

**Comment by BlueMaple** [comment]
@louisbao 我也遇到了同样的问题。。。你试试把package.json里面的"weex-loader": "^0.2.0"改为"weex-loader": "0.2.0"，或者其他低版本。

**Comment by iwilsonlee** [comment]
@louisbao 我也遇到了同样的问题。不过按照 @BlueMaple 提供的解决方案去做之后，可以成功跑起来了。感谢两位！^^

**Comment by louisbao** [comment]
@BlueMaple @iwilsonlee 非常感谢，确实是这个问题！
