### ISSUE TITLE
 Uncaught TypeError: apis.getHome is not a function

### ISSUE THREAD

**Issue by rjliulei** [dodola/WeexOne#16]
我把WeexOne直接放到Weex中在电脑上运行，chrome浏览器显示 Uncaught TypeError: apis.getHome is not a function，这是什么原因？

**Comment by flazx** [comment]
我哦也遇到同样的问题，貌似webpack没有将apis中的export函数内容打包进去而导致的。

**Comment by liujianying** [comment]
我的也一样,知道怎么解决么

**Comment by liujianying** [comment]
ERROR in ./examples/WeexOne/modules/movie-video.we?entry=true
Template block is required

ERROR in ./examples/WeexOne/common/api.js
Module not found: Error: Cannot resolve module '@weex-module/stream' in /Users/liujianying/Desktop/weex-dev/examples/WeexOne/common
 @ ./examples/WeexOne/common/api.js 6:13-43

ERROR in ./examples/WeexOne/common/api.js
Module not found: Error: Cannot resolve module '@weex-module/modal' in /Users/liujianying/Desktop/weex-dev/examples/WeexOne/common
 @ ./examples/WeexOne/common/api.js 7:12-41

**Comment by dodola** [comment]
现在不会有这个问题了
