### ISSUE TITLE
在js文件中怎么 require('@weex-module/stream');？我这边会报错

### ISSUE THREAD

**Issue by Rowandjj** [dodola/WeexOne#2]
如题

**Comment by dodola** [comment]
@Rowandjj 提示什么错误

**Comment by Rowandjj** [comment]
@dodola can not resolve module xxx.  我问过勾股了，他说目前还不支持js中引用。但是很奇怪，我将你的代码放到playground中执行，是可以的。

**Comment by Rowandjj** [comment]
@dodola can not resolve module xxx.  我问过勾股了，他说目前还不支持js中引用。但是很奇怪，我将你的代码放到playground中执行，是可以的。

**Comment by dodola** [comment]
@Rowandjj 他可能理解错你的意思了

**Comment by zeuscoder** [comment]
@Rowandjj 我和你遇到同样的问题，api.js会放在自己的项目中会报同样的错，放在playground中却可以执行，请问你解决这种情况了吗？

**Comment by joywt** [comment]
请问这个问题解决方法是什么？能把这个问题放出来吗？

**Comment by Mignet** [comment]
我也遇到这个问题，项目源码是https://github.com/charlescui/weex-baji
第一步，我通过weexpack init Hweex创建了一个新项目Hweex。
第二步，我把weex-baji中的modules、model、images文件夹和index.we文件copy到新项目的src目录下。
第三步，我在新项目Hweex下执行weexpack run android，报错得到一个 Cannot resolve module underscore和 Cannot resolve module  '@weex-module/stream' in E:\backend\Hweex\src\model
 @ ./src/model/channel.js 6:13-43
第四步，我在Hweex下执行npm install underscore，然后执行weexpack run android
依然得到ERROR in ./src/model/channel.js
Module not found: Error: Cannot resolve module '@weex-module/stream' in E:\backend\Hweex\src\model
 @ ./src/model/channel.js 6:13-43
我该怎么解决？

**Comment by Mignet** [comment]
我已经找到了，当前的确不支持，只能用黑魔法^^
https://github.com/weexteam/article/issues/20
