### ISSUE TITLE
hello weexone server api hung up

### ISSUE THREAD

**Issue by sunnycn2013** [dodola/WeexOne#20]
hello,hello weexone server api hung up. as  I'm in the browser with 'http://v3.wufazhuce.com:8000/api//hp/bymonth/2016-06', it's Invalid.
![simulator screen shot 2016 9 25 8 03 39](https://cloud.githubusercontent.com/assets/3810388/18811989/baf6d0c6-82f6-11e6-96e4-42e6ec27eac2.png)

**Comment by dodola** [comment]
@sunnycn2013 thanks for your feedback ,I will fix it

**Comment by BadWooden** [comment]
ERROR in ./examples/WeexOne/modules/movie-video.we?entry=true
什么编译是这个错误

**Comment by dodola** [comment]
fixed all
