### ISSUE TITLE
Open android/playground是哪里呢？

### ISSUE THREAD

**Issue by JakeWoki** [dodola/WeexOne#21]
找不到

**Comment by dodola** [comment]
@JakeWoki 哦，不好意思，这个首页document比较久了，就是和weex首页的过程一样，改ip，

**Comment by JakeWoki** [comment]
@dodola weex的首页也没改，没看到那里说改ip

**Comment by dodola** [comment]
@JakeWoki 在这里
1. Open android/playground
2. In app/java/com.alibaba.weex/IndexActivity, modify CURRENT_IP to your local IP

**Comment by JakeWoki** [comment]
![image](https://github.com/JakeWoki/android-open-project/blob/master/11111.png?raw=true)
![image](https://github.com/JakeWoki/android-open-project/blob/master/2222.png?raw=true)
在浏览器会打开，但是只有底部导航，没有数据

**Comment by JakeWoki** [comment]
![image](https://github.com/JakeWoki/android-open-project/blob/master/333.png?raw=true)

**Comment by JakeWoki** [comment]
Add WeexOne to index.we后运行没有WeexOne，In Weex project folder run ./start这一步是什么？

**Comment by JakeWoki** [comment]
修改CURRENT_IP为本地ip是指手机的ip吗？改了不行呢

**Comment by JakeWoki** [comment]
@dodola 编译错误
$ weex init
$ npm install
$ npm run dev
提示ERROR in Cannot find module 'babel-core'
 @ ./src/main.we?entry=true 3:22-488
