### ISSUE TITLE
安卓或者苹果手机调试main.we文件，页面显示不出来

### ISSUE THREAD

**Issue by jingxin2015** [dodola/WeexOne#22]
如题，我的执行步骤是这样的：
1、在cmd上执行 weex debug src/main.we -h 192.168.2.108 弹出来调试页面
2、扫描左边的二维码，上面识别出来手机信息，再扫描第2个二维码，手机上会出来页面，但是页面如下图所示，不知道什么原因？
![qq 20161021233259](https://cloud.githubusercontent.com/assets/16143766/19604461/ec998f14-97e7-11e6-813d-1fc740ae6bbb.png)

**Comment by dodola** [comment]
@jingxin2015 你这样执行是有问题的，不过我已经将代码离线存到android 端了，可以看一下weexone/android下的目录，你可以在build后将代码拷贝到assets文件夹里，最近也在做weexpack的一些修改
