### ISSUE TITLE
weex跨域问题

### ISSUE THREAD

**Issue by sunshiner** [dodola/WeexOne#5]
weex现在不支持跨域，想问下博主是怎么解决跨域问题的

**Comment by dodola** [comment]
@sunshiner 你说的是 Web 运行方式的么？

**Comment by dodola** [comment]
@sunshiner 我这个开发的时候只考虑了 Android 端，没有遇到跨域的问题

**Comment by sunshiner** [comment]
ok，ths

**Comment by JashonWang** [comment]
楼主，我想请教一个问题，为什么你的接口都不存在跨域问题呢？就算是在web端运行也完全正常。
