### ISSUE TITLE
package.json没有？

### ISSUE THREAD

**Issue by nicefe** [dodola/WeexOne#6]
弱弱的问句，好像根目录下没有package.json，怎么执行npm install 安装相关的模块呀。

**Comment by dodola** [comment]
@nicefe 我只把源码部分提交了，其他部分的代码都属于Weex项目的，请从这里获取 https://github.com/alibaba/weex

**Comment by nicefe** [comment]
哦哦，了解。。表示还没有资格ಥ_ಥ。好尴尬，谢谢了。

**Comment by dodola** [comment]
@nicefe 你需要先申请一下Weex的权限，http://alibaba.github.io/weex/#subscriptionWeex
