### ISSUE TITLE
android按照步骤做了后，运行playground，无更新。listview中没有weekone这一项。

### ISSUE THREAD

**Issue by PengLL** [dodola/WeexOne#7]

**Comment by dodola** [comment]
@PengLL 你有在例子的 index.we 中增加选项么     {name: ‘WeexOne/index.js’, title: ‘WeexOne’}

**Comment by PengLL** [comment]
增加了的。
我的操作步骤：
1.androidstudio打开playground，更改current_ip.为我的localIP
2.将clone下来的weexone-master中的weexone文件夹拷贝到了weex项目的example文件夹中
3.在index.we添加选项{name: ‘WeexOne/index.js’, title: ‘WeexOne’}
4.weex根目录下npm install ,     ./start执行命令的结果都正常
4.运行playground
列表里面没有增加weexone选项，其他选项正常的

我进行了两种测试;
1.我把index.we中某一个选项进行了更改，例如{name: 'hello', title: 'Hello World'}的title改为hello
{name: 'hello', title: 'Hello'}然后install， ./start。但是playground中第一项依然是hello world，并没改成hello
2.我更改了hello.we中的内容，例如将hello world改为hello，然后install  ./start.这时手机上的playground中hello world选项的内容得到了更新，变为了hello。

**Comment by 2010jing** [comment]
@PengLL 我也是遇到一样问题

**Comment by fengshanjian** [comment]
改成{name: ‘WeexOne/index’, title: ‘WeexOne’} 即可解决

**Comment by dodola** [comment]
@fengshanjian 👍，我用的那个版本之前还需要增加后缀，现在貌似去掉了

**Comment by JakeWoki** [comment]
androidstudio的playground是什么？
