### ISSUE TITLE
无法刷新出页面

### ISSUE THREAD

**Issue by sunnyyin** [dodola/WeexOne#8]
按照步骤，无法刷新出页面，一直在加载，请问是什么原因呢？

**Comment by tomkai** [comment]
readme里面有个错误
{name: ‘WeexOne/index.js’, title: ‘WeexOne’}   应该不带.js后缀
index.we里面注释已经说明了
// `name` key is the example filename without '.we'
应用不带后缀的

你把后缀去掉就OK了

**Comment by dodola** [comment]
已经修复
